CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    nickname VARCHAR(255),
    password_hash VARCHAR(255),
    provider VARCHAR(255) NOT NULL,
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    verification_token VARCHAR(255),
    verification_token_expires_at TIMESTAMPTZ,
    reset_token VARCHAR(255),
    reset_token_expires_at TIMESTAMPTZ,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_nickname UNIQUE (nickname)
);

CREATE INDEX IF NOT EXISTS idx_users_verification_token ON users (verification_token);
CREATE INDEX IF NOT EXISTS idx_users_reset_token ON users (reset_token);

CREATE TABLE IF NOT EXISTS user_stats (
    user_id UUID PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    small_wins INTEGER NOT NULL DEFAULT 0,
    medium_wins INTEGER NOT NULL DEFAULT 0,
    large_wins INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_user_stats_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

ALTER TABLE IF EXISTS user_stats
    ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;

UPDATE user_stats
SET version = 0
WHERE version IS NULL;

ALTER TABLE IF EXISTS user_stats
    ALTER COLUMN version SET DEFAULT 0,
    ALTER COLUMN version SET NOT NULL;

ALTER TABLE IF EXISTS user_stats
    ADD COLUMN IF NOT EXISTS small_wins INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS medium_wins INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS large_wins INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_name VARCHAR(255) NOT NULL DEFAULT '',
    user_id UUID NOT NULL,
    author_email VARCHAR(255) NOT NULL DEFAULT '',
    rating INTEGER NOT NULL,
    comment VARCHAR(150),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_date DATE NOT NULL DEFAULT CURRENT_DATE,
    CONSTRAINT fk_feedback_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_feedback_rating
        CHECK (rating >= 1 AND rating <= 5)
);

CREATE INDEX IF NOT EXISTS idx_feedback_created_at ON feedback (created_at);
CREATE INDEX IF NOT EXISTS idx_feedback_author_email_created_at ON feedback (author_email, created_at DESC);

CREATE TABLE IF NOT EXISTS recorded_wins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    game_id VARCHAR(255) NOT NULL,
    board_size VARCHAR(16) NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_recorded_wins_user_game UNIQUE (user_id, game_id)
);

CREATE INDEX IF NOT EXISTS idx_recorded_wins_user_id ON recorded_wins (user_id);
CREATE INDEX IF NOT EXISTS idx_recorded_wins_game_id ON recorded_wins (game_id);
